"""parcel_events

Revision ID: fe038862beb8
Revises: 7e3982e99fa4
Create Date: 2026-10-10 09:19:40.453926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe038862beb8'
down_revision: Union[str, Sequence[str], None] = '7e3982e99fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parcel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.CheckConstraint("status NOT IN ('pickup_assigned', 'picked_up', 'delivery_assigned', 'out_for_delivery', 'delivered', 'failed') OR courier_id IS NOT NULL", name='chk_parcel_events_courier'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parcel_events_courier', 'parcel_events', ['courier_id', 'status', 'occurred_at'], unique=False)
    op.create_index('idx_parcel_events_parcel', 'parcel_events', ['parcel_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parcel_events_parcel', table_name='parcel_events')
    op.drop_index('idx_parcel_events_courier', table_name='parcel_events')
    op.drop_table('parcel_events')
    # ### end Alembic commands ###
